services:
  backend:
    container_name: linktree-be
    image: linktree/linktree-be
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - /backend/.env
    depends_on:
      - database
  database:
    container_name: linktree-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
